language: ruby
cache: bundler
rvm:
- 2.6
- 2.4

before_install:
- gem update --system
- gem install bundler

before_script: bundle update
script: script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false
